version: '3.8'
services:

  destpg:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dest_db
    ports:
      - "5433:5432"
    networks:
      - airflow_network
    volumes:
      - "./ny_taxi_pg_data:/var/lib/postgresql/data:rw"
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - airflow_network
    depends_on:
      - destpg

volumes:
  pgadmin_data: